[package]
name = "limail"
version = "0.1.0"
authors = ["Lakin Wecker <lakin@wecker.ca>"]

[dependencies]
slack = "0.22.0"
dotenv = "0.15.0"
rocket = "0.4.2"
rocket_contrib = "0.4.2"
hmac = "0.7.1"
sha2 = "0.8.0"
hex = "0.3.1"
reqwest = "0.9.22"
log = "0.4.0"
env_logger = "0.7.1"
